# Generated by Django 5.0.2 on 2024-03-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='integer_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
