# Generated by Django 5.0.2 on 2024-03-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_habit_completed_habit_end_time_habit_integer_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='integer_value',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='start_time',
        ),
        migrations.AddField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('integer', 'Integer'), ('yes_no', 'Yes/No'), ('timer', 'Timer')], default='yes_no', max_length=10),
        ),
    ]
