# Generated by Django 5.0.2 on 2024-04-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_habit_completed_remove_habit_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.TextField(default=''),
        ),
    ]
