# Generated by Django 5.0.2 on 2024-04-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_habit_frequency_delete_habitcompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='habit_type',
        ),
    ]
