# Generated by Django 5.0.2 on 2024-04-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_habit_habit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
